# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lenovo\Documents\projects\lindu2\src\bmkg2pha.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(555, 47)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.line_bmkgpath = QtWidgets.QLineEdit(Form)
        self.line_bmkgpath.setObjectName("line_bmkgpath")
        self.horizontalLayout.addWidget(self.line_bmkgpath)
        self.btn_bmkgOpen = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bmkgOpen.sizePolicy().hasHeightForWidth())
        self.btn_bmkgOpen.setSizePolicy(sizePolicy)
        self.btn_bmkgOpen.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_bmkgOpen.setObjectName("btn_bmkgOpen")
        self.horizontalLayout.addWidget(self.btn_bmkgOpen)
        self.btn_bmkgConvert = QtWidgets.QPushButton(Form)
        self.btn_bmkgConvert.setObjectName("btn_bmkgConvert")
        self.horizontalLayout.addWidget(self.btn_bmkgConvert)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.line_phasepath = QtWidgets.QLineEdit(Form)
        self.line_phasepath.setEnabled(True)
        self.line_phasepath.setReadOnly(True)
        self.line_phasepath.setObjectName("line_phasepath")
        self.horizontalLayout_2.addWidget(self.line_phasepath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BMKG to PHA"))
        self.label_2.setText(_translate("Form", "BMKG catalog file:  "))
        self.btn_bmkgOpen.setText(_translate("Form", "..."))
        self.btn_bmkgConvert.setText(_translate("Form", "Convert"))
        self.label.setText(_translate("Form", "to phase.dat:             "))
